version: 2

builds:
  # Mac build - uses native macOS cargo
  - id: "motus-macos"
    builder: rust
    binary: motus
    targets:
      - aarch64-apple-darwin # Native target for Apple Silicon
    dir: "."
    tool: "cargo"
    command: build
    flags:
      - --release
      - -p=cli

  # Linux build - uses cross for cross-compilation via Docker
  - id: "motus-linux"
    builder: rust
    binary: motus
    targets:
      - x86_64-unknown-linux-gnu
    dir: "."
    tool: "cross" # Use cross instead of cargo
    command: build
    flags:
      - --release
      - -p=cli
    env:
      - CARGO_NET_GIT_FETCH_WITH_CLI=true # Helps with git authentication in Docker

# macOS specific configuration for archives
archives:
  - id: motus-archives
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: darwin
        format: zip
      - goos: linux
        format: tar.gz
    files:
      - LICENSE
      - README.md

# Linux package configuration (DEB)
nfpms:
  - id: motus-packages
    package_name: motus
    file_name_template: "{{ .PackageName }}_{{ .Version }}_{{ .Arch }}"

    vendor: Théo Crevon
    homepage: https://github.com/oleiade/motus
    maintainer: Théo Crevon <theo@crevon.me>
    description: A simple and elegant password generator
    license: MIT

    section: utils
    priority: optional

    contents:
      - src: LICENSE
        dst: /usr/share/doc/motus/LICENSE
      - src: README.md
        dst: /usr/share/doc/motus/README.md

    # Generate only DEB packages for now
    formats:
      - apk
      - deb
      - rpm
